stages:
  - test
  - pages

test:
  stage: test
  before_script:
    - npm ci
  script:
    - npm run lint

pages:
  stage: pages
  script:
    - npm ci
    - npm run build-dev
  artifacts:
    paths:
    - public
  only:
    - master
