version: 2

defaults: &defaults
  docker:
    - image: circleci/node:13-browsers

git_restore_cache: &git_restore_cache
  restore_cache:
    keys:
      - source-v1-{{ .Branch }}-{{ .Revision }}
      - source-v1-{{ .Branch }}-
      - source-v1-

git_save_cache: &git_save_cache
  save_cache:
    key: source-v1-{{ .Branch }}-{{ .Revision }}
    paths:
      - ".git"

jobs:
  test_and_build:
    <<: *defaults
    steps:
      - *git_restore_cache
      - checkout
      - *git_save_cache
      - run:
          name: Install
          command: npm ci
      - run:
          name: Test
          command: npm test
      - run:
          name: Build
          command: npm run build
  test_and_build_and_deploy_to_npm:
    <<: *defaults
    steps:
      - *git_restore_cache
      - checkout
      - *git_save_cache
      - run:
          name: Install
          command: npm ci
      - run:
          name: Build
          command: npm run build
      - run:
          name: Deploy to npm
          command: npm publish --access public

workflows:
  version: 2
  ci:
    jobs:
      - test_and_build:
          filters:
            branches:
              ignore: npm
      - test_and_build_and_deploy_to_npm:
          filters:
            branches:
              only: npm
